#: import FadeTransition kivy.uix.screenmanager.FadeTransition

<CloneMenu>

    canvas.before:
        Color:
            rgba: 0, 0, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size
    
    FloatLayout:

        ImageButton:
            size_hint: 1, 0.6
            pos_hint: {"center_x": 0.5, "center_y": 0.7}
            source: "Assets/map_blur.png"

        ImageButton:
            size_hint: 0.2, 0.1
            pos_hint: {"center_x": 0.125, "center_y": 0.95}
            source: "Assets/back.png"
            on_release:
                root.manager.transition = FadeTransition(duration=0.09)
                root.manager.current = 'MainMenu'
        Label:
            size_hint: 1, 0.1
            pos_hint: {"center_x": 0.125, "center_y": 0.90}
            text: "Back"
            font_size: "12sp"
            color: "#aaaaaa"
            font_name: root.font

        GridLayout:
            size_hint: .9, None
            height: "40dp"
            pos_hint: {"center_x": 0.5, "center_y": 0.8}
            cols: 2
            spacing: 3
            padding: 3
            canvas:
                Color:
                    group: "outline-color"
                    rgba: 0, 0.110, 0.175, 1

                Line:
                    width: 1.1
                    rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, self.height
            
            TextInput:
                id: Clone_Input
                markup: True 
                font_name: root.font
                hint_text: "Enter Your Proxy to clone..."
                hint_text_color: "#00aaff55"
                size_hint_x: 0.7
                background_normal: ''
                background_color: "#101010CC"
                foreground_color: "ffff00"
                height: 40
                padding_y: (self.height - self.line_height) / 2
                multiline: False

            Button:
                text: "Clone"
                size_hint_x: 0.3
                markup: True 
                font_name: "Assets/font.ttf"
                background_color: "#ff000022"
                background_normal: ''
                background_down: 'ff000011'
                on_release:
                    root.clone_vless(Clone_Input, Clone_Output, Clone_Nums) if Clone_Input.text.startswith("vless://") else root.clone_vmess(Clone_Input, Clone_Output, Clone_Nums)
        
        GridLayout:
            size_hint: .9, None
            height: "40dp"
            pos_hint: {"center_x": 0.5, "center_y": 0.7}
            cols: 2
            spacing: 3
            padding: 3
            canvas:
                Color:
                    group: "outline-color"
                    rgba: 0, 0.110, 0.175, 1

                Line:
                    width: 1.1
                    rounded_rectangle: self.x, self.y, self.width, self.height, 5, 5, 5, 5, self.height
            
            Slider:
                id: Clone_Nums
                size_hint_x: 0.8
                value_track: True
                value_track_color: "#2980B9"
                value_track_width: "3.9sp"
                min: 2
                max: 50
                step: 1
                cursor_height: "28sp"
                cursor_width: "28sp"
                cursor_image: "Assets/slider.png"

            Label:
                size_hint_x: 0.2
                text: str(int(Clone_Nums.value))
                color: "#ffffff"
                font_name: "RobotoMono-Regular.ttf"
        
        ScrollView:
            pos_hint: {"center_x": 0.5, "center_y": 0.3}
            size_hint: 0.9, 0.55
            do_scroll_x: False
            bar_color: "#008080"
            bar_width: 1
            canvas:
                Color:
                    group: "outline-color"
                    rgba: 0, 0.110, 0.175, 1

                Line:
                    width: 1.1
                    rounded_rectangle: self.x, self.y, self.width, self.height, 0, 0, 5, 5, self.height

            GridLayout:
                cols: 1
                size_hint: 1, None
                height: self.minimum_height
                spacing: "10dp"

                Label:
                    id: Clone_Output
                    text: "All cloned proxies will be shown here.\n\nYou can select how many clone you want from 1 clone to 50 clones.\nYou can copy cloned proxies by clicking on Copy button next to generated proxies.\n\nThe entered proxy will be detected automatically and supported proxies are:\n    + Vless\n    + Vmess\n\nNote that there is no QRcode option here. You can access QRcode option in main menu when you generates your proxy.\n\n"
                    markup: True 
                    font_name: "RobotoMono-Regular.ttf"
                    size_hint_y: None
                    height: self.texture_size[1]
                    text_size: self.width, None
                    padding: 10, 10

                Button:
                    pos_hint: {"center_x": 0.5}
                    text: "Copy to clipboard"
                    height: "40dp"
                    size_hint_y: None
                    padding: 10, 10
                    markup: True 
                    font_name: "Assets/font.ttf"
                    background_color: "#008080"
                    background_normal: ''
                    background_down: 'ff000011'
                    color: "#ffffff"
                    on_release:
                        root.copy_to_clipboard(Clone_Output)